name: 'Setup Knative'
description: 'This action sets up Knative using Knative quick start plugin'
author: 'Zhaofeng Miao'
branding:
  icon: anchor
  color: blue
runs:
  using: 'node16'
  main: 'src/index.js'